# -*- coding: utf-8 -*-
"""Exploratory Data Analysis (EDA) of Diabetes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Isc2-nbqpc2G9g6ZHsIh2xSjxYqVC2ul

# **Explorartory Data Analysis of Diabetes**

**Md. Rakibul Hasan**
<br> Civil Engineer
<br> Disaster Management (Contd.), University of Dhaka, Bangladesh


**Questions for the Assignment:**
<br> [1] Question: What is the correlation between features in the dataset. and what two features have very strong correlation with the independent variable? Justify with reason
<br> [2] Question: Which feature has more outliers. Explain with a visualization.
<br> [3] Question: In which Age group Majority of people have diabetes? Make a visualization to validate your finding.

**Reference:**
<br> **Dataset Source**: https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv

## **Importing required libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_context("talk")
sns.set_style("darkgrid")

"""####**Loading Dataset**"""

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv')

print(df.head(10))

"""####**Checking the number of rows and column in the dataset**"""

df.shape

"""**Number of rows** = 768
<br> **Number of columns** = 9

####**Unique features in the dataset**
"""

df.columns

"""####**Checking the data types and any missing values present in the dataset**"""

df.info()

"""Number of rows = 768
<br> Number of columns = 9
<br> Number of integar cells = 7: (Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, Age, Outcome)
<br> Number of float cells = 2: (BMI, DiabetesPedigreeFunction)
<br> ***The dataset has no missing values.***
"""

df.isnull().sum()

"""#### **Statistics of the dataframe**"""

df.describe()

"""***Numerical summary of each column***

#### **Unique values for 'Outcome' column**
"""

df.Outcome.unique()

"""Here, All the values either 0 or 1
<br> by the way, Outcome indicates if a person is diagnosed with diabetes
<br> **0** means non-diabetic
<br> **1** means diabetic (i.e. person is diagnosed with diabetes)
"""

plt.figure(figsize = (8,6))
sns.countplot('Outcome',data=df)
plt.show()

"""####**Examining correlation between the features in the dataset**"""

df_cor = df.corr()

display(df_cor)

plt.figure(figsize=(12,10))
sns.heatmap(df_cor, annot=True, cmap="RdYlGn", vmax=1, vmin=-1)
plt.title("Pearson Correlation Coefficient between the features")
plt.show()

df.corr().nlargest(n = 3, columns = 'Outcome')

"""From the above figure and table we can say that, **2 features** have very strong correlation with the independent variable **'Outcome'** which are:
<br> **Glocose** = **0.47**
<br> **BMI** = **0.29**

#### **Feature which has more outliers**
"""

plt.figure(figsize = (15,10))
sns.boxplot(x="Pregnancies", y="Age", data=df, hue="Outcome")
plt.show()

"""#### **Showing Age group for Majority of people have diabetes**"""

plt.figure(figsize = (22,15))
sns.countplot('Age', hue = "Outcome", data = df)
plt.show()